name: cellpose4
channels:
  - conda-forge
  - defaults

dependencies:
  # ---- Core Python version ----
  - python=3.10.18

  # ---- Scientific stack (conda-forge: stable LAPACK/BLAS) ----
  - numpy=1.26.4
  - pandas=2.3.2
  - scipy=1.15.3
  - pillow=10.4.0
  - scikit-learn=1.5.2
  - scikit-image=0.25.2
  - tifffile=2024.9.20

  # Conda pip
  - pip

  # ---- Everything pip-only goes here ----
  - pip:
      - cellpose==3.1.1.2
      - tensorflow==2.16.2
      - keras==3.10.0
      - torch==2.5.1
      - torchvision==0.20.1
      - optuna==4.6.0
      - opencv-python
      - sam2==1.1.0
      - huggingface_hub==1.1.2
      - plotly==6.3.1
      - streamlit==1.51.0
      - streamlit-image-coordinates==0.4.0
