[theme]
base = "light"
primaryColor = "#004280ff"             # medium sky-blue (for highlights, buttons)
backgroundColor = "#ffffffff"          # main background (pale blue-gray)
secondaryBackgroundColor = "#ebf1f7ff" # cards / containers
textColor = "#004280ff"                # soft navy text
font = "sans serif"
